= Kreativitätstechniken (Jan Brunner)

== Brainstorming (Jan Brunner)
* Beim Brainstorming sollen die Teilnehmer/innen *(5 bis 7)* zu einem Problem oder Ziel Ideen und Lösungen entwickeln. Die Ideen werden mündlich geäußert - andere Teilnehmer/innen können dadurch inspiriert werden. Alle Ideen werden deutlich sichtbar mitprotokolliert. Ein/e Moderator/in steuert und überwacht den Brainstormingprozess. Das Brainstorming dauert zwischen *10 und 20 Minuten*. Die Bewertung der Vorschläge darf erst in einer zweiten Phase erfolgen.

== Regeln beim Brainstorming (Jan Brunner)
* Freies Assoziieren und Fantasieren sind erwünscht. (egal wie unrealistisch)
* Es sollen möglichst viele Ideen erzeugt werden.
* Während der Phase der Ideensammlung darf keine Kritik an den Ideen geübt werden! (Sonst denkt sich die Person macht es doch selbst, oder er wird bei der Ideenfindung behindert).

== Methode 6-3-5 / Brainwriting (Jan Brunner)
* *6 Teilnehmer/innen*
* *3 Ideen*
* *5 Minuten*
* *Durchführung*: Es schreibt jeder Teilnehmer/in 3 Ideen in 5 Minuten auf ein Blatt. Nach 5 Minuten wird das Blatt weitergereicht. Nach 30 Minuten sind es dann 108 Ideen. Die Regeln sind die gleichen wie beim normalen Brainstorming. Die Aufzeichnung erfolgt am besten mit einem Formular.

== Synektische Methode (Jan Brunner)

*Synektische Methode = Systematische Verfremdung*

=== Ablauf (Jan Brunner)

*1.* Beschäftigen mit dem Problem (Sammlung und Strukturierung von Informationen)

*2.* Ablenken vom Problem (Verfremdung des Sachverhalts)

*3.* Schaffen von Verbindungen zwischen Problem und Verfremdung.

*4.* "spontanes" Bewusstwerden von Lösungsideen

Man benötigt für diese Methode 8 - 12 Personen und einen Moderator. Sie dauert meist einige Stunden bis mehrere Tage. Für effektiven Einsatz der Synektik sind Kreativität, Flexibilität sowie ein positives Gruppenklima erforderlich.


== Morphologischer Kasten (Jan Brunner)
* Entwickelt von Schweizer Fritz Zwicky (1898 - 1974) wird somit auch als "Zwicky-Box" bezeichnet.
* Der Morphologische Kasten unterstützt das systematische Auffinden aller Lösungsvarianten zu einem gegebenen Problem.
* Durch diese Systematik können sehr einfach alle möglichen sowie unmöglichen Kombinationen gebildet werden.
* Der Morphologische Kasten hilft dabei, verschiedene Aspekte oder Merkmale einer (Projekt)-Lösung systematisch anzuordnen. Er trägt dazu bei, die ideale Kombination aus einer Fülle von Merkmalen zu finden. 

=== Ablauf:

* Definieren der Aufgabenstellung
* Festlegen der Teilbereiche (1. Spalte, müssen voreinander unabhängig sein, max. 6-7)
* Festlegen der Ausprägungen zu jedem Teilbereich auch diese sollte möglichst unabhängig sein.
* Definieren der verschiedenen Lösungsvarianten (Linie ziehen)
* Analyse und Auswahl der Lösung(en)
